name: Publish Project

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # SemVer

env:
  CHANGELOG_LOCATION: "Changelog is available [here](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }})"
  RELEASE_TYPE: 'beta'

concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pre-release:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    name: Create Tag Release (Auto)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project
        run: ./gradlew build --warning-mode all --build-cache

      - name: Rename JARs with commit hash
        run: |
          short_sha=$(git rev-parse --short=6 HEAD)
          for f in build/libs/*.jar; do
            base=$(basename "$f" .jar)
            mv "$f" "build/libs/${base}-${short_sha}.jar"
          done

      - name: Tag and Draft GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          short_sha=$(git rev-parse --short HEAD)
          tag_name="auto-${short_sha}"
          git tag "$tag_name"
          git push origin "$tag_name"
          gh release create "$tag_name" \
            --repo "$GITHUB_REPOSITORY" \
            --title "Auto Build - $short_sha" \
            --notes "Automatic build for commit $short_sha" \
            --prerelease \
            build/libs/*.jar

  full-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Full Release (SemVer)
    permissions:
      contents: write

    env:
      DISABLE_BUILDSCRIPT_UPDATE_CHECK: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project
        run: ./gradlew build --warning-mode all --build-cache

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "build/libs/*.jar"
          generate_release_notes: true
          fail_on_unmatched_files: true
